### ISSUE TITLE
请问这个支持Android4.0~5.0之间的系统么

### ISSUE THREAD

**Issue by cloudsafe** [h2oiswater/react-native-nova-alipay#3]

**Comment by h2oiswater** [comment]
RN 0.45的环境下，真机6.0，虚拟机7.0测试ok
4.0 ~ 5.0理论上没问题
RN 0.47报错的BUG有大兄弟提了PR我这里测试了就上传npm

**Comment by cloudsafe** [comment]
我之前用的是yunpeng的，android4.4.4直接蹦。我fork是以防万一你这个也蹦，所以。。。。
我看着你用的是比较新的sdk应该没大问题。我有修改的话，就提

**Comment by h2oiswater** [comment]
好的

**Comment by h2oiswater** [comment]
有问题吗？android4.4.4

**Comment by cloudsafe** [comment]
还没试支付流程，但是，嵌入目前没有问题。
