### ISSUE TITLE
配置好后，调用支付提示：“暂时无法获取订单信息，请稍后重试”。这是什么问题啊？

### ISSUE THREAD

**Issue by 401537200** [h2oiswater/react-native-nova-alipay#4]
配置好后，调用支付提示：“暂时无法获取订单信息，请稍后重试”。这是什么问题啊？

**Comment by h2oiswater** [comment]
签名字符串有问题

**Comment by 401537200** [comment]
这个是支付宝秘钥签名问题，好好检查一下。




------------------ 原始邮件 ------------------
发件人: "龚江鹏";<notifications@github.com>;
发送时间: 2017年10月25日(星期三) 晚上8:29
收件人: "h2oiswater/react-native-nova-alipay"<react-native-nova-alipay@noreply.github.com>;
抄送: "雨划过的天空"<401537200@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [h2oiswater/react-native-nova-alipay] 配置好后，调用支付提示：“暂时无法获取订单信息，请稍后重试”。这是什么问题啊？ (#4)




Closed #4.
