### ISSUE TITLE
default.pay is undefined

### ISSUE THREAD

**Issue by koo1006** [h2oiswater/react-native-nova-alipay#6]
Hi I love your plugin alot. It actually no problem with the android version. But the ios i getting issue "Alipay.default.pay is undefined". Did you have any solution?

Thanks

Here is my packaging version
```
"react": "^15.4.2",
    "react-native": "^0.42.3",
```

**Comment by h2oiswater** [comment]
1. react-native link
2.Config
Added the following libraries to your "Link Binary With Libraries":

 CoreMotion.framework
 CoreTelephony.framework
 libc++
 libz
add URL Schema as your app id for URL type in Targets - info

Make sure you have these code in AppDelegate.m to enable callback

#import "AlipayModule.h"
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  [AlipayModule handleCallback:url];
  return YES;
}

**Comment by h2oiswater** [comment]
Make sure you have done all steps above ^_^

**Comment by koo1006** [comment]
Sorry my mistake. Thanks it work now 👍
